config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get 'welcome/index'
  root 'welcome#index'

  #resources :candidatos
  resources :vagas, param: :vaga_id do #avisando que parametro p/ vaga sera vaga id
    member do
      resources :candidatos
    end
  end
  resources :usuarios, except: [:show] do
    get 'meu_perfil', on: :collection, to: 'usuarios#show' #rota nona com verbo get chamada meu meu_perfil

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vaga.rb
class Vaga < ApplicationRecord
  has_many :candidatos
  belongs_to :usuario

  validates :titulo, :salario, :modelo, presence: true

end

app/controllers/vagas_controller.rb
class VagasController < ApplicationController
  before_action :set_vaga, only: %i[ show edit update destroy ]

  #p/ acessar action precisa se logar
  before_action :authenticate_usuario!

  # GET /vagas or /vagas.json
  def index
    @vagas = current_usuario.vagas #Vaga do usuario logado/ que usuario tem ascesso
  end

  # GET /vagas/1 or /vagas/1.json
  def show
  end

  # GET /vagas/new
  def new
    @vaga = Vaga.new
  end

  # GET /vagas/1/edit
  def edit
  end

  # POST /vagas or /vagas.json
  def create
    @vaga = current_usuario.vagas.new(vaga_params)#Criando uma nova vaga p/ um usuario

    respond_to do |format|
      if @vaga.save
        format.html { redirect_to vaga_url(@vaga), notice: "Vaga was successfully created." }
        format.json { render :show, status: :created, location: @vaga }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vaga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vagas/1 or /vagas/1.json
  def update
    respond_to do |format|
      if @vaga.update(vaga_params)
        format.html { redirect_to vaga_url(@vaga), notice: "Vaga was successfully updated." }
        format.json { render :show, status: :ok, location: @vaga }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vaga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vagas/1 or /vagas/1.json
  def destroy
    @vaga.destroy

    respond_to do |format|
      format.html { redirect_to vagas_url, notice: "Vaga was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaga
      @vaga = Vaga.find(params[:vaga_id])
    end

    # Only allow a list of trusted parameters through.
    def vaga_params
      params.require(:vaga).permit(:titulo, :salario, :modelo, :local)
    end
end

app/helpers/vagas_helper.rb
module VagasHelper
end

app/views/vagas/_form.html.erb
<%= form_with(model: vaga, local: true) do |form| %>
  <% if vaga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vaga.errors.count, "error") %> prohibited this vaga from being saved:</h2>

      <ul>
      <% vaga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :vaga_titulo %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.text_field :salario, id: :vaga_salario %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo, id: :vaga_modelo %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local, id: :vaga_local %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vagas/edit.html.erb
<h1>Editar Vaga</h1>

<%= render 'form', vaga: @vaga %>

<%= link_to 'Exibir', @vaga %> |
<%= link_to 'Voltar', vagas_path %>

app/views/vagas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Vagas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Salario</th>
      <th>Modelo</th>
      <th>Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vagas.each do |vaga| %>
      <tr>
        <td><%= vaga.titulo %></td>
        <td><%= vaga.salario %></td>
        <td><%= vaga.modelo %></td>
        <td><%= vaga.local %></td>
        <td><%= link_to 'Exibir Vaga', vaga %></td>
        <td><%= link_to 'Editar', edit_vaga_path(vaga) %></td>
        <td><%= link_to 'Candidatos', candidatos_path(vaga) %></td>
        <td><%= link_to 'Apagar', vaga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<hr>
<ul>
  <li><%= current_usuario.nome %></li>
  <br>
  <br>
  <li><%= link_to 'Nova Vaga', new_vaga_path %></li>
  <br>
  <li><%= link_to 'Voltar', welcome_index_path %></li>
</ul>

app/views/vagas/new.html.erb
<h1>Nova Vaga</h1>

<%= render 'form', vaga: @vaga %>

<%= link_to 'Voltar', vagas_path %>

app/views/vagas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @vaga.titulo %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @vaga.salario %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @vaga.modelo %>
</p>

<p>
  <strong>Local:</strong>
  <%= @vaga.local %>
</p>

<%= link_to 'Editar', edit_vaga_path(@vaga) %> |
<%= link_to 'Voltar', vagas_path %>