config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get 'welcome/index'
  root 'welcome#index'

  #resources :candidatos
  resources :vagas, param: :vaga_id do #avisando que parametro p/ vaga sera vaga id
    member do
      resources :candidatos
    end
  end
  resources :usuarios, except: [:show] do
    get 'meu_perfil', on: :collection, to: 'usuarios#show' #rota nona com verbo get chamada meu meu_perfil

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidato.rb
class Candidato < ApplicationRecord
  belongs_to :vaga

  validates :nome, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :set_candidato, only: %i[ show edit update destroy ]
  before_action :set_vaga

  #p/ acessar action precisa se logar
  before_action :authenticate_usuario!

  # GET /candidatos or /candidatos.json
  def index
    @candidatos = @vaga.candidatos #candidatos da vaga informada pela url
  end

  # GET /candidatos/1 or /candidatos/1.json
  def show
  end

  # GET /candidatos/new
  def new
    @candidato = Candidato.new
  end

  # GET /candidatos/1/edit
  def edit
  end

  # POST /candidatos or /candidatos.json
  def create
    @candidato = @vaga.candidatos.new(candidato_params)

    respond_to do |format|
      if @candidato.save
        format.html { redirect_to candidato_url(@vaga, @candidato), notice: "Candidato was successfully created." }
        format.json { render :show, status: :created, location: @candidato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidatos/1 or /candidatos/1.json
  def update
    respond_to do |format|
      if @candidato.update(candidato_params)
        format.html { redirect_to candidato_url(@vaga, @candidato), notice: "Candidato was successfully updated." }
        format.json { render :show, status: :ok, location: @candidato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidatos/1 or /candidatos/1.json
  def destroy
    @candidato.destroy

    respond_to do |format|
      format.html { redirect_to candidatos_url, notice: "Candidato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidato
      @candidato = Candidato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def candidato_params
      params.require(:candidato).permit(:nome, :email, :telefone, :escolaridade, :exp_profissional)
    end
    def set_vaga

      @vaga = Vaga.find(params[:vaga_id])
    end
end

app/helpers/candidatos_helper.rb
module CandidatosHelper
end

app/views/candidatos/_form.html.erb
<%= form_with(model: candidato, local: true, url: "/vagas/#{@vaga.id}/candidatos/#{@candidato.id}") do |form| %>
  <% if candidato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidato.errors.count, "error") %> prohibited this candidato from being saved:</h2>

      <ul>
      <% candidato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :candidato_nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :candidato_email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :candidato_telefone %>
  </div>

  <div class="field">
    <%= form.label :escolaridade %>
    <%= form.text_field :escolaridade, id: :candidato_escolaridade %>
  </div>

  <div class="field">
    <%= form.label :exp_profissional %>
    <%= form.text_field :exp_profissional, id: :candidato_exp_profissional %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candidatos/edit.html.erb
<h1>Editar Candidato</h1>

<%= render 'form', candidato: @candidato %>

<%= link_to 'Show', @candidato %> |
<%= link_to 'Voltar', candidatos_path %>

app/views/candidatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Candidatos</h1>
<h3><%= @vaga.titulo %></h3>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Escolaridade</th>
      <th>Exp profissional</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidatos.each do |candidato| %>
      <tr>
        <td><%= candidato.nome %></td>
        <td><%= candidato.email %></td>
        <td><%= candidato.telefone %></td>
        <td><%= candidato.escolaridade %></td>
        <td><%= candidato.exp_profissional %></td>
        <td><%= link_to 'Perfil', candidato_path(@vaga, candidato) %></td>
        <td><%= link_to 'Editar', edit_candidato_path(@vaga, candidato) %></td>
        <td><%= link_to 'Apagar', candidato_path(@vaga, candidato), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<ul>
  <li><%= link_to 'Novo Candidato', new_candidato_path %></li>
  <li><%= link_to 'Voltar', vagas_path %></li>
</ul>

app/views/candidatos/new.html.erb
<h1>Novo Candidato</h1>

<%= render 'form', candidato: @candidato %>

<%= link_to 'Voltar', candidatos_path %>

app/views/candidatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @candidato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidato.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @candidato.telefone %>
</p>

<p>
  <strong>Escolaridade:</strong>
  <%= @candidato.escolaridade %>
</p>

<p>
  <strong>Exp profissional:</strong>
  <%= @candidato.exp_profissional %>
</p>

<%= link_to 'Editar', edit_candidato_path(@candidato) %> |
<%= link_to 'Voltar', candidatos_path %>